name: bookme
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  image_picker: ^1.0.1
  flutter_rating_bar: ^4.0.1
  im_stepper: ^1.0.1+1
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/


